# Generated by Django 4.2.7 on 2023-11-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('SERIES', 'Séries'), ('FILMES', 'Filmes'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros')], max_length=15),
        ),
    ]
