# Generated by Django 4.2.7 on 2023-11-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.movie'),
        ),
    ]
